title: Confidential Computing Notes
markdown: kramdown
kramdown:
  input: GFM
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
permalink: pretty
defaults:
  -
    scope:
      path: ""
    values:
      custom_css: assets/css/custom.css
